<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByProducts($name)
	{
		$qb = $repository
            ->createQueryBuilder('p')
            ->where('p.name LIKE :name')
            ->setParameter('name', "%$name%")
            ->orderBy('p.name', 'ASC')
            ->getQuery()
        ;

        return $qb
			->getQuery()
			->getResult()
		;
	}
}
