<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPrqmjx9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPrqmjx9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPrqmjx9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPrqmjx9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

<<<<<<< Updated upstream
return new \Container5xevlke\appProdProjectContainer(array(
    'container.build_hash' => '5xevlke',
    'container.build_id' => '2a8b9d31',
    'container.build_time' => 1531241163,
), __DIR__.\DIRECTORY_SEPARATOR.'Container5xevlke');
=======
return new \ContainerPrqmjx9\appProdProjectContainer(array(
    'container.build_hash' => 'Prqmjx9',
    'container.build_id' => 'e9ce3fe3',
    'container.build_time' => 1531234000,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPrqmjx9');
>>>>>>> Stashed changes
