<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xevlke\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xevlke/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5xevlke.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5xevlke\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5xevlke\appProdProjectContainer(array(
    'container.build_hash' => '5xevlke',
    'container.build_id' => '0b785007',
    'container.build_time' => 1530881978,
), __DIR__.\DIRECTORY_SEPARATOR.'Container5xevlke');
