<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZrbf7t3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZrbf7t3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZrbf7t3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZrbf7t3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZrbf7t3\appProdProjectContainer(array(
    'container.build_hash' => 'Zrbf7t3',
    'container.build_id' => '3809fb89',
    'container.build_time' => 1525076670,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZrbf7t3');
