AppBundle\Entity\Categorie:
    type:  entity
    table: category
    id:
        id:
            type:     integer
            nullable: false
            options:
                unsigned: false
            id:       true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type:     string
            nullable: false
            length:   100
            options:
                fixed: false
        bg:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
    lifecycleCallbacks: {  }
