AppBundle\Entity\Clients:
    type:  entity
    table: clients
    id:
        clientId:
            type:     integer
            nullable: false
            options:
                unsigned: false
            id:       true
            column:       client_id
            generator:
                strategy: IDENTITY
    fields:
        clientName:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   client_name
        clientFirstname:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   client_firstname
        clientPhone:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   client_phone
    lifecycleCallbacks:   {  }
