AppBundle\Entity\Client:
    type:  entity
    table: client
    id:
        id:
            type:     integer
            nullable: false
            options:
                unsigned: false
            id:       true
            column:       id
            generator:
                strategy: IDENTITY
    fields:
<<<<<<< HEAD
        alias:
=======
        lastName:
>>>>>>> searchbar
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
<<<<<<< HEAD
            column:   alias
=======
            column:   last_name
>>>>>>> searchbar
        firstName:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   first_name
        phone:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   phone
<<<<<<< HEAD
    lifecycleCallbacks:   {  }
=======
    lifecycleCallbacks: {  }
>>>>>>> searchbar
