AppBundle\Entity\Cpu:
    type:  entity
    table: cpu
    id:
        cpuId:
            type:     integer
            nullable: false
            options:
                unsigned: false
            id:       true
            column:   cpu_id
            generator:
                strategy: IDENTITY
    fields:
        cpuCoreNumber:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   cpu_core_number
        cpuFrequency:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   cpu_frequency
        cpuCache:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   cpu_cache
        cpuArchitecture:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   cpu_architecture
        cpuSocket:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   cpu_socket
        cpuThermalDissipation:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   cpu_thermal_dissipation
    lifecycleCallbacks: {  }
