AppBundle\Entity\Gpu:
    type:  entity
    table: gpu
    id:
        gpuId:
            type:     integer
            nullable: false
            options:
                unsigned: false
            id:       true
            column:   gpu_id
            generator:
                strategy: IDENTITY
    fields:
        gpuModel:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   gpu_model
        gpuFrequency:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   gpu_frequency
        gpuInterface:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   gpu_interface
        gpuMemory:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   gpu_memory
        gpuMemoryFrequency:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   gpu_memory_frequency
        gpuDetails:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   gpu_details
    lifecycleCallbacks: {  }
