AppBundle\Entity\Products:
    type: entity
    table: products
    id:
        productId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: product_id
            generator:
                strategy: IDENTITY
    fields:
        productModel:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: product_model
        productReference:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: product_reference
        productBrand:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: product_brand
        productPrice:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: product_price
        productStock:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: product_stock
        productWeight:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: product_weight
        productDimension:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: product_dimension
        productDiscount:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: product_discount
        productDescription:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: product_description
    lifecycleCallbacks: {  }
