AppBundle\Entity\Product:
    type:  entity
    table: product
    id:
        id:
            type:     integer
            nullable: false
            options:
                unsigned: false
            id:       true
            generator:
                strategy: IDENTITY
    fields:
        idCategory:
            type:     integer
            nullable: true
            options:
                unsigned: false
            column:   id_category
        name:
            type:     string
            nullable: true
            length:   255
            options:
                fixed: false
        productDescription:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   product_description
        productBrand:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   product_brand
        productPrice:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   product_price
        productStock:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   product_stock
        productWeight:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   product_weight
        productDimensions:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   product_dimensions
        productDiscount:
            type:     string
            nullable: false
            length:   255
            options:
                fixed: false
            column:   product_discount
    lifecycleCallbacks: {  }
