AppBundle\Entity\PurchaseProduct:
    type:  entity
    table: purchase_product
    id:
        purchaseId:
            type:     integer
            nullable: false
            options:
                unsigned: false
            id:       true
            column:   purchase_id
            generator:
                strategy: IDENTITY
    fields:
        productId:
            type:     integer
            nullable: false
            options:
                unsigned: false
            column:   product_id
        productsNumber:
            type:     integer
            nullable: false
            options:
                unsigned: false
            column:   products_number
        totalPrice:
            type:     integer
            nullable: false
            options:
                unsigned: false
            column:   total_price
    lifecycleCallbacks: {  }
