<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMpwvkw0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMpwvkw0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMpwvkw0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMpwvkw0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMpwvkw0\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Mpwvkw0',
    'container.build_id' => '6ac2b347',
    'container.build_time' => 1531241086,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMpwvkw0');
