<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU7c2kqu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU7c2kqu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerU7c2kqu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerU7c2kqu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerU7c2kqu\appDevDebugProjectContainer(array(
    'container.build_hash' => 'U7c2kqu',
    'container.build_id' => '2a8dc600',
    'container.build_time' => 1530795669,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerU7c2kqu');
