<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Products extends \AppBundle\Entity\Products implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productId', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productModel', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productReference', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productBrand', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productPrice', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productStock', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productWeight', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productDimension', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productDiscount', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productDescription'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productId', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productModel', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productReference', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productBrand', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productPrice', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productStock', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productWeight', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productDimension', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productDiscount', '' . "\0" . 'AppBundle\\Entity\\Products' . "\0" . 'productDescription'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Products $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getProductId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProductId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductId', []);

        return parent::getProductId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductModel($productModel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductModel', [$productModel]);

        return parent::setProductModel($productModel);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductModel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductModel', []);

        return parent::getProductModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductReference($productReference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductReference', [$productReference]);

        return parent::setProductReference($productReference);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductReference', []);

        return parent::getProductReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductBrand($productBrand)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductBrand', [$productBrand]);

        return parent::setProductBrand($productBrand);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductBrand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductBrand', []);

        return parent::getProductBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductPrice($productPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductPrice', [$productPrice]);

        return parent::setProductPrice($productPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductPrice', []);

        return parent::getProductPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductStock($productStock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductStock', [$productStock]);

        return parent::setProductStock($productStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductStock', []);

        return parent::getProductStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductWeight($productWeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductWeight', [$productWeight]);

        return parent::setProductWeight($productWeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductWeight', []);

        return parent::getProductWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductDimension($productDimension)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductDimension', [$productDimension]);

        return parent::setProductDimension($productDimension);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductDimension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductDimension', []);

        return parent::getProductDimension();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductDiscount($productDiscount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductDiscount', [$productDiscount]);

        return parent::setProductDiscount($productDiscount);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductDiscount', []);

        return parent::getProductDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductDescription($productDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductDescription', [$productDescription]);

        return parent::setProductDescription($productDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductDescription', []);

        return parent::getProductDescription();
    }

}
