<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Motherboard extends \AppBundle\Entity\Motherboard implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Motherboard' . "\0" . 'motherboardId', '' . "\0" . 'AppBundle\\Entity\\Motherboard' . "\0" . 'motherboardSocket', '' . "\0" . 'AppBundle\\Entity\\Motherboard' . "\0" . 'motherboardChipset', '' . "\0" . 'AppBundle\\Entity\\Motherboard' . "\0" . 'motherboardPorts', '' . "\0" . 'AppBundle\\Entity\\Motherboard' . "\0" . 'motherboardMaxFreq', '' . "\0" . 'AppBundle\\Entity\\Motherboard' . "\0" . 'motherboardSataController'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Motherboard' . "\0" . 'motherboardId', '' . "\0" . 'AppBundle\\Entity\\Motherboard' . "\0" . 'motherboardSocket', '' . "\0" . 'AppBundle\\Entity\\Motherboard' . "\0" . 'motherboardChipset', '' . "\0" . 'AppBundle\\Entity\\Motherboard' . "\0" . 'motherboardPorts', '' . "\0" . 'AppBundle\\Entity\\Motherboard' . "\0" . 'motherboardMaxFreq', '' . "\0" . 'AppBundle\\Entity\\Motherboard' . "\0" . 'motherboardSataController'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Motherboard $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMotherboardId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMotherboardId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotherboardId', []);

        return parent::getMotherboardId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotherboardSocket($motherboardSocket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotherboardSocket', [$motherboardSocket]);

        return parent::setMotherboardSocket($motherboardSocket);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotherboardSocket()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotherboardSocket', []);

        return parent::getMotherboardSocket();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotherboardChipset($motherboardChipset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotherboardChipset', [$motherboardChipset]);

        return parent::setMotherboardChipset($motherboardChipset);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotherboardChipset()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotherboardChipset', []);

        return parent::getMotherboardChipset();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotherboardPorts($motherboardPorts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotherboardPorts', [$motherboardPorts]);

        return parent::setMotherboardPorts($motherboardPorts);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotherboardPorts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotherboardPorts', []);

        return parent::getMotherboardPorts();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotherboardMaxFreq($motherboardMaxFreq)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotherboardMaxFreq', [$motherboardMaxFreq]);

        return parent::setMotherboardMaxFreq($motherboardMaxFreq);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotherboardMaxFreq()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotherboardMaxFreq', []);

        return parent::getMotherboardMaxFreq();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotherboardSataController($motherboardSataController)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotherboardSataController', [$motherboardSataController]);

        return parent::setMotherboardSataController($motherboardSataController);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotherboardSataController()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotherboardSataController', []);

        return parent::getMotherboardSataController();
    }

}
