<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ram extends \AppBundle\Entity\Ram implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ram' . "\0" . 'ramId', '' . "\0" . 'AppBundle\\Entity\\Ram' . "\0" . 'ramType', '' . "\0" . 'AppBundle\\Entity\\Ram' . "\0" . 'ramCapacity', '' . "\0" . 'AppBundle\\Entity\\Ram' . "\0" . 'ramFrequency', '' . "\0" . 'AppBundle\\Entity\\Ram' . "\0" . 'ramTimings', '' . "\0" . 'AppBundle\\Entity\\Ram' . "\0" . 'ramTension'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ram' . "\0" . 'ramId', '' . "\0" . 'AppBundle\\Entity\\Ram' . "\0" . 'ramType', '' . "\0" . 'AppBundle\\Entity\\Ram' . "\0" . 'ramCapacity', '' . "\0" . 'AppBundle\\Entity\\Ram' . "\0" . 'ramFrequency', '' . "\0" . 'AppBundle\\Entity\\Ram' . "\0" . 'ramTimings', '' . "\0" . 'AppBundle\\Entity\\Ram' . "\0" . 'ramTension'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ram $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRamId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getRamId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRamId', []);

        return parent::getRamId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRamType($ramType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRamType', [$ramType]);

        return parent::setRamType($ramType);
    }

    /**
     * {@inheritDoc}
     */
    public function getRamType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRamType', []);

        return parent::getRamType();
    }

    /**
     * {@inheritDoc}
     */
    public function setRamCapacity($ramCapacity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRamCapacity', [$ramCapacity]);

        return parent::setRamCapacity($ramCapacity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRamCapacity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRamCapacity', []);

        return parent::getRamCapacity();
    }

    /**
     * {@inheritDoc}
     */
    public function setRamFrequency($ramFrequency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRamFrequency', [$ramFrequency]);

        return parent::setRamFrequency($ramFrequency);
    }

    /**
     * {@inheritDoc}
     */
    public function getRamFrequency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRamFrequency', []);

        return parent::getRamFrequency();
    }

    /**
     * {@inheritDoc}
     */
    public function setRamTimings($ramTimings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRamTimings', [$ramTimings]);

        return parent::setRamTimings($ramTimings);
    }

    /**
     * {@inheritDoc}
     */
    public function getRamTimings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRamTimings', []);

        return parent::getRamTimings();
    }

    /**
     * {@inheritDoc}
     */
    public function setRamTension($ramTension)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRamTension', [$ramTension]);

        return parent::setRamTension($ramTension);
    }

    /**
     * {@inheritDoc}
     */
    public function getRamTension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRamTension', []);

        return parent::getRamTension();
    }

}
