<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cpu extends \AppBundle\Entity\Cpu implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuId', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuCoreNumber', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuFrequency', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuCache', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuArchitecture', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuSocket', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuThermalDissipation'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuId', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuCoreNumber', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuFrequency', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuCache', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuArchitecture', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuSocket', '' . "\0" . 'AppBundle\\Entity\\Cpu' . "\0" . 'cpuThermalDissipation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cpu $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCpuId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCpuId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpuId', []);

        return parent::getCpuId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpuCoreNumber($cpuCoreNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpuCoreNumber', [$cpuCoreNumber]);

        return parent::setCpuCoreNumber($cpuCoreNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpuCoreNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpuCoreNumber', []);

        return parent::getCpuCoreNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpuFrequency($cpuFrequency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpuFrequency', [$cpuFrequency]);

        return parent::setCpuFrequency($cpuFrequency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpuFrequency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpuFrequency', []);

        return parent::getCpuFrequency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpuCache($cpuCache)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpuCache', [$cpuCache]);

        return parent::setCpuCache($cpuCache);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpuCache()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpuCache', []);

        return parent::getCpuCache();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpuArchitecture($cpuArchitecture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpuArchitecture', [$cpuArchitecture]);

        return parent::setCpuArchitecture($cpuArchitecture);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpuArchitecture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpuArchitecture', []);

        return parent::getCpuArchitecture();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpuSocket($cpuSocket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpuSocket', [$cpuSocket]);

        return parent::setCpuSocket($cpuSocket);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpuSocket()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpuSocket', []);

        return parent::getCpuSocket();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpuThermalDissipation($cpuThermalDissipation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpuThermalDissipation', [$cpuThermalDissipation]);

        return parent::setCpuThermalDissipation($cpuThermalDissipation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpuThermalDissipation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpuThermalDissipation', []);

        return parent::getCpuThermalDissipation();
    }

}
